language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: banyudu@gmail.com
  api_key:
    secure: lMtglMXBqY3M4OakLTxa+oqkXvoN5Ku3lHkV6lN+ipkuD+zrBSZn60KPCuKnvAqEzIGrGx3D1LNWeKfZ+GVrB0OF2+hQo8vjRyLujn38mQPP7TxC66SvwqQ6ZUirMO1PmnJJBWm4aMKlSYDMkiYmkJaX14f9ypRLqZotTc75JL8RyI4E+fOMNU0nj3JBk7xJSMJko+QNEU5mizrQF4ByY2hgEMpNTdzzgfS8CQPZoXD3UpY1pDKKNSMth4bf9tiZLo2HGgM/bUWv3ROIAf2KSqS5+KU0vt8dbkj3ad4LJL1r1gKVsCP3ct3Jmr4S3SN63QiCZhMABtnCQpyoDfgqzx9mPDbpgmsBhnyyzcCaQlUwfhcUHC/f3zBPb8C9P81Ix9eVtqZCxDPqwvgQ+vWrEyl980d29mEoXIOGUJmq3G68o9M1pTez7EYjeBqGDOc2+TDVzqMUvpKyQE7dCGDtuF/wNY1dCVlo4zG4bPfMkZpLhp+C1CSJHx0AbTHXY4mflydWqBCP7dvzB61zUV+jQ8Jmn7UZIF9boRrrzijuuL4RXjXNqWbyepQvUucySfPFER9+1RlLnLl6GUf3wGZFHw4QYuMPUktIq8pf2XJu7fS3GeFt4gp5++GARUe2wh2F+zlJKMXDmrqtY/YZWY7auYSoWglfz+CsbNQe4r1ZOtA=
  on:
    tags: true
    branch: master
  tag: latest
